DEFAULT_KB_ICON = "library"

ALLOWED_KB_ICONS = frozenset(
    {
        "library",
        "book-open",
        "book-marked",
        "book",
        "book-copy",
        "bookmark",
        "scroll-text",
        "notebook",
        "notebook-pen",
        "file-text",
        "file",
        "files",
        "folder",
        "folder-open",
        "folders",
        "archive",
        "database",
        "hard-drive",
        "server",
        "cloud",
        "brain",
        "lightbulb",
        "sparkles",
        "bot",
        "cpu",
        "network",
        "globe",
        "search",
        "scan-search",
        "graduation-cap",
        "school",
        "microscope",
        "flask-conical",
        "atom",
        "scale",
        "briefcase",
        "building",
        "building-2",
        "factory",
        "chart-bar",
        "chart-line",
        "pie-chart",
        "target",
        "compass",
        "map",
        "map-pin",
        "heart",
        "star",
        "tag",
        "tags",
        "layers",
        "layout-grid",
        "grid-3x3",
        "box",
        "package",
        "inbox",
        "message-square",
        "messages-square",
        "pen-line",
        "clipboard-list",
        "code",
        "terminal",
        "wrench",
        "shield",
        "lock",
        "key",
        "users",
        "user",
        "hash",
        "link",
        "share-2",
        "rocket",
        "zap",
        "calendar",
        "clock",
        "list-todo",
        "table",
        "kanban",
        "git-branch",
        "workflow",
    }
)


def normalize_kb_icon(icon: str | None) -> str:
    if not icon or not str(icon).strip():
        return DEFAULT_KB_ICON
    normalized = str(icon).strip().lower()
    if normalized not in ALLOWED_KB_ICONS:
        raise ValueError(
            f"Invalid icon '{icon}'. Allowed: {', '.join(sorted(ALLOWED_KB_ICONS))}"
        )
    return normalized
