import type { KbIconName } from "@/lib/kb-icons";

const KB_ICON_LABELS_EN: Record<KbIconName, string> = {
  library: "Library",
  "book-open": "Open book",
  "book-marked": "Bookmarked book",
  book: "Book",
  "book-copy": "Book copy",
  bookmark: "Bookmark",
  "scroll-text": "Scroll",
  notebook: "Notebook",
  "notebook-pen": "Notes",
  "file-text": "Document",
  file: "File",
  files: "Files",
  folder: "Folder",
  "folder-open": "Open folder",
  folders: "Folders",
  archive: "Archive",
  database: "Database",
  "hard-drive": "Storage",
  server: "Server",
  cloud: "Cloud",
  brain: "Brain",
  lightbulb: "Ideas",
  sparkles: "Sparkles",
  bot: "Bot",
  cpu: "Compute",
  network: "Network",
  globe: "Globe",
  search: "Search",
  "scan-search": "Scan",
  "graduation-cap": "Education",
  school: "School",
  microscope: "Research",
  "flask-conical": "Science",
  atom: "Science",
  scale: "Legal",
  briefcase: "Business",
  building: "Building",
  "building-2": "Office",
  factory: "Industry",
  "chart-bar": "Bar chart",
  "chart-line": "Line chart",
  "pie-chart": "Pie chart",
  target: "Target",
  compass: "Compass",
  map: "Map",
  "map-pin": "Location",
  heart: "Favorite",
  star: "Star",
  tag: "Tag",
  tags: "Tags",
  layers: "Layers",
  "layout-grid": "Grid",
  "grid-3x3": "Matrix",
  box: "Box",
  package: "Package",
  inbox: "Inbox",
  "message-square": "Chat",
  "messages-square": "Chats",
  "pen-line": "Writing",
  "clipboard-list": "Checklist",
  code: "Code",
  terminal: "Terminal",
  wrench: "Tools",
  shield: "Security",
  lock: "Lock",
  key: "Key",
  users: "Team",
  user: "User",
  hash: "Hash",
  link: "Link",
  "share-2": "Share",
  rocket: "Launch",
  zap: "Fast",
  calendar: "Calendar",
  clock: "Schedule",
  "list-todo": "Todo",
  table: "Table",
  kanban: "Kanban",
  "git-branch": "Branch",
  workflow: "Workflow",
};

const KB_ICON_LABELS_ZH: Record<KbIconName, string> = {
  library: "书库",
  "book-open": "书本",
  "book-marked": "书签",
  book: "书籍",
  "book-copy": "副本",
  bookmark: "书签",
  "scroll-text": "卷轴",
  notebook: "笔记本",
  "notebook-pen": "笔记",
  "file-text": "文档",
  file: "文件",
  files: "多文件",
  folder: "文件夹",
  "folder-open": "打开文件夹",
  folders: "文件夹组",
  archive: "归档",
  database: "数据库",
  "hard-drive": "存储",
  server: "服务器",
  cloud: "云端",
  brain: "智能",
  lightbulb: "灵感",
  sparkles: "亮点",
  bot: "机器人",
  cpu: "算力",
  network: "网络",
  globe: "全球",
  search: "搜索",
  "scan-search": "检索",
  "graduation-cap": "教育",
  school: "学校",
  microscope: "科研",
  "flask-conical": "实验",
  atom: "科学",
  scale: "法律",
  briefcase: "商务",
  building: "建筑",
  "building-2": "办公",
  factory: "工业",
  "chart-bar": "柱状图",
  "chart-line": "折线图",
  "pie-chart": "饼图",
  target: "目标",
  compass: "指南",
  map: "地图",
  "map-pin": "地点",
  heart: "收藏",
  star: "星标",
  tag: "标签",
  tags: "多标签",
  layers: "分层",
  "layout-grid": "网格",
  "grid-3x3": "矩阵",
  box: "盒子",
  package: "包裹",
  inbox: "收件箱",
  "message-square": "对话",
  "messages-square": "多对话",
  "pen-line": "写作",
  "clipboard-list": "清单",
  code: "代码",
  terminal: "终端",
  wrench: "工具",
  shield: "安全",
  lock: "锁定",
  key: "密钥",
  users: "团队",
  user: "用户",
  hash: "话题",
  link: "链接",
  "share-2": "分享",
  rocket: "发布",
  zap: "快速",
  calendar: "日历",
  clock: "日程",
  "list-todo": "待办",
  table: "表格",
  kanban: "看板",
  "git-branch": "分支",
  workflow: "流程",
};

export function getKbIconLabel(name: KbIconName, locale: string): string {
  return locale === "zh" ? KB_ICON_LABELS_ZH[name] : KB_ICON_LABELS_EN[name];
}
