import type { LucideIcon } from "lucide-react";
import {
  Archive,
  Atom,
  Book,
  BookCopy,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calendar,
  ChartBar,
  ChartLine,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Compass,
  Cpu,
  Database,
  Factory,
  File,
  Files,
  FileText,
  FlaskConical,
  Folder,
  FolderOpen,
  Folders,
  GitBranch,
  Globe,
  GraduationCap,
  Grid3x3,
  HardDrive,
  Hash,
  Heart,
  Inbox,
  Kanban,
  Key,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  Map,
  MapPin,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Network,
  Notebook,
  NotebookPen,
  Package,
  PenLine,
  PieChart,
  Rocket,
  Scale,
  ScanSearch,
  School,
  ScrollText,
  Search,
  Server,
  Share2,
  Shield,
  Sparkles,
  Star,
  Table,
  Tag,
  Tags,
  Target,
  Terminal,
  User,
  Users,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

export const DEFAULT_KB_ICON = "library" as const;

export const KB_ICON_NAMES = [
  "library",
  "book-open",
  "book-marked",
  "book",
  "book-copy",
  "bookmark",
  "scroll-text",
  "notebook",
  "notebook-pen",
  "file-text",
  "file",
  "files",
  "folder",
  "folder-open",
  "folders",
  "archive",
  "database",
  "hard-drive",
  "server",
  "cloud",
  "brain",
  "lightbulb",
  "sparkles",
  "bot",
  "cpu",
  "network",
  "globe",
  "search",
  "scan-search",
  "graduation-cap",
  "school",
  "microscope",
  "flask-conical",
  "atom",
  "scale",
  "briefcase",
  "building",
  "building-2",
  "factory",
  "chart-bar",
  "chart-line",
  "pie-chart",
  "target",
  "compass",
  "map",
  "map-pin",
  "heart",
  "star",
  "tag",
  "tags",
  "layers",
  "layout-grid",
  "grid-3x3",
  "box",
  "package",
  "inbox",
  "message-square",
  "messages-square",
  "pen-line",
  "clipboard-list",
  "code",
  "terminal",
  "wrench",
  "shield",
  "lock",
  "key",
  "users",
  "user",
  "hash",
  "link",
  "share-2",
  "rocket",
  "zap",
  "calendar",
  "clock",
  "list-todo",
  "table",
  "kanban",
  "git-branch",
  "workflow",
] as const;

export type KbIconName = (typeof KB_ICON_NAMES)[number];

export const KB_ICONS: Record<KbIconName, LucideIcon> = {
  library: Library,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  book: Book,
  "book-copy": BookCopy,
  bookmark: Bookmark,
  "scroll-text": ScrollText,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  "file-text": FileText,
  file: File,
  files: Files,
  folder: Folder,
  "folder-open": FolderOpen,
  folders: Folders,
  archive: Archive,
  database: Database,
  "hard-drive": HardDrive,
  server: Server,
  cloud: Cloud,
  brain: Brain,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  bot: Bot,
  cpu: Cpu,
  network: Network,
  globe: Globe,
  search: Search,
  "scan-search": ScanSearch,
  "graduation-cap": GraduationCap,
  school: School,
  microscope: Microscope,
  "flask-conical": FlaskConical,
  atom: Atom,
  scale: Scale,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  factory: Factory,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "pie-chart": PieChart,
  target: Target,
  compass: Compass,
  map: Map,
  "map-pin": MapPin,
  heart: Heart,
  star: Star,
  tag: Tag,
  tags: Tags,
  layers: Layers,
  "layout-grid": LayoutGrid,
  "grid-3x3": Grid3x3,
  box: Box,
  package: Package,
  inbox: Inbox,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "pen-line": PenLine,
  "clipboard-list": ClipboardList,
  code: Code,
  terminal: Terminal,
  wrench: Wrench,
  shield: Shield,
  lock: Lock,
  key: Key,
  users: Users,
  user: User,
  hash: Hash,
  link: Link,
  "share-2": Share2,
  rocket: Rocket,
  zap: Zap,
  calendar: Calendar,
  clock: Clock,
  "list-todo": ListTodo,
  table: Table,
  kanban: Kanban,
  "git-branch": GitBranch,
  workflow: Workflow,
};

export function isKbIconName(value: string | null | undefined): value is KbIconName {
  return KB_ICON_NAMES.includes(value as KbIconName);
}

export function resolveKbIconName(value: string | null | undefined): KbIconName {
  return isKbIconName(value) ? value : DEFAULT_KB_ICON;
}

export function getKbIconComponent(value: string | null | undefined): LucideIcon {
  return KB_ICONS[resolveKbIconName(value)];
}
